version: '0.0.2'
source: "https://github.com/tr7zw/ModComposeTemplate/tree/1.20"
replacements:
  group: "dev.tr7zw"
  name: "Exordium"
  id: "exordium"
  version: "1.1.3"
  author: "tr7zw"
  dependencies: '
  modImplementation "maven.modrinth:immediatelyfast:1.1.16+1.20.1"

      implementation("com.github.LlamaLad7:MixinExtras:0.1.1")

      include "com.github.LlamaLad7:MixinExtras:0.1.1"

      annotationProcessor("com.github.LlamaLad7:MixinExtras:0.1.1")
  '
  relocationpackage: "dev.tr7zw.exordium"
  licensename: "LICENSE"
  modrinthid: "DynYZEae"
enabledFlags:
  - autopublish
  - publishFabric
  - modrinth
  - curseforge
  - accesswidener
rootProject:
  template: "."
subProjects:
  FG-Fabric:
    template: "Fabric"
