version: '0.0.2'
source: "https://github.com/tr7zw/ProcessedModTemplate/tree/master"
replacements:
  name: "Exordium"
  id: "exordium"
  version: "1.4.1"
  description: "Renders the UI at a lower framerate to give the gameplay more legroom."
  homepageUrl: "https://modrinth.com/mod/exordium"
  sourcesUrl: "https://github.com/tr7zw/Exordium"
  issuesUrl: "https://github.com/tr7zw/Exordium/issues"
  fabric_entrypoint: "dev.tr7zw.exordium.ExordiumMod"
  fabric_modmenu_entrypoint: "dev.tr7zw.exordium.ExordiumModMenu"
  relocationpackage: "dev.tr7zw.exordium"
  licensename: "LICENSE-Exordium"
  modrinthid: DynYZEae
  curseforgeid: 681953
  versionlessname: "Exordium-Versionless"
  fabric_dependencies: "\n    modImplementation 'net.fabricmc.fabric-api:fabric-api:0.128.2+1.21.7'\n    modCompileOnly 'curse.maven:xaerominimap-263420:5394788'\n    "
enabledFlags:
  - autopublish
  - publishFabric
  - modrinth
  - curseforge
  - versionless
rootProject:
  template: "."
subProjects:
  Exordium-Versionless:
    template: "Versionless"
    replacements:
      dependencies: '\n\n      compileOnly "com.google.code.gson:gson:2.10.1"\n\n      compileOnly "org.apache.logging.log4j:log4j-core:2.20.0"\n      '