version: '0.0.2'
source: "https://github.com/tr7zw/ModComposeTemplate/tree/1.20.4"
replacements:
  group: "dev.tr7zw"
  name: "Exordium"
  id: "exordium"
  version: "1.2.1"
  author: "tr7zw"
  relocationpackage: "dev.tr7zw.exordium"
  licensename: "LICENSE"
  modrinthid: "DynYZEae"
  curseforgeid: "681953"
enabledFlags:
  - autopublish
  - publishFabric
  - publishForge
  - modrinth
  - curseforge
  - accesswidener
rootProject:
  template: "."
subProjects:
  FG-Fabric:
    template: "Fabric"
    replacements:
      dependencies: '
          modImplementation "maven.modrinth:immediatelyfast:1.2.10+1.20.4-fabric"
          
          modImplementation "maven.modrinth:spark:1.10.58-fabric"
          
          //modImplementation "maven.modrinth:sodium:mc1.20.4-0.5.8"
      '
  FG-Forge:
    template: "Forge"
    replacements:
      dependencies: '
      compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.3.5"))
      
      implementation(include("io.github.llamalad7:mixinextras-forge:0.3.5"))
      '